name: Build AbyssVideoDownloader

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build AbyssVideoDownloader
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Clone Repository
        run: |
          git clone https://github.com/tienphong923/AbyssVideoDownloader.git
          cd AbyssVideoDownloader

      - name: Make Gradle Executable
        run: chmod +x AbyssVideoDownloader/gradlew

      - name: Build AbyssVideoDownloader
        run: |
          cd AbyssVideoDownloader
          ./gradlew build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: v1.5
          name: AbyssVideoDownloader-v${{ github.run_number }}
          files: AbyssVideoDownloader/build/libs/abyss-dl.jar
          draft: true
